[tool.ruff]
select = ["E", "F", "I"]
line-length = 100
exclude = [
    "build",
    "doc",
    "*__init__.py"
]
# The minimum Python version that should be supported
target-version = "py38"

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"